import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ConfidenceBadge } from "@/components/ConfidenceBadge";
import { SourceChip } from "@/components/SourceChip";
import { Icon } from "@/components/Icon";
import { getLexemeBySlug } from "@/lib/server/repositories";
import type { Source } from "@/lib/types";

type PageProps = { params: Promise<{ slug: string }> };
export const dynamic = "force-dynamic";

function description(value: string | null) {
  return (value || "A source-linked lexeme record with deterministic values by named system.").replace(/\s+/g, " ").slice(0, 158);
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const record = getLexemeBySlug(decodeURIComponent(slug));
  if (!record) return { title: "Term not found" };
  return {
    title: `${record.lexeme.text} (${record.lexeme.transliteration || record.lexeme.language})`,
    description: description(record.lexeme.gloss),
    alternates: { canonical: `/term/${encodeURIComponent(slug)}` },
    openGraph: { title: `${record.lexeme.text} · Gematria Lab`, description: description(record.lexeme.gloss), type: "article" },
  };
}

export default async function TermPage({ params }: PageProps) {
  const { slug } = await params;
  const record = getLexemeBySlug(decodeURIComponent(slug));
  if (!record) notFound();
  const termUrl = `https://gematria-lab.saulspodship.com/term/${encodeURIComponent(slug)}`;
  const schema = {
    "@context": "https://schema.org", "@type": "DefinedTerm", name: record.lexeme.text,
    alternateName: record.lexeme.transliteration || undefined, description: record.lexeme.gloss || undefined,
    inLanguage: record.lexeme.language, url: termUrl,
    citation: record.lexemeSources.map((item: any) => item.source.url).filter(Boolean),
  };
  const faq = {
    "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
      { "@type": "Question", name: "Are gematria values generated by AI?", acceptedAnswer: { "@type": "Answer", text: "No. Gematria values are computed deterministically from visible lookup tables, with per-letter values shown." } },
      { "@type": "Question", name: "Does a shared value prove that two words are connected?", acceptedAnswer: { "@type": "Answer", text: "No. A shared value is a numerical observation only. The coincidence baseline shows how often matches occur in the current reference catalog." } },
    ],
  };
  const safeJson = (value: unknown) => JSON.stringify(value).replace(/</g, "\\u003c");
  return <main className="document-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJson(schema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJson(faq) }} />
    <Link className="document-back" href="/"><Icon name="arrow" size={14} /> Back to research lab</Link>
    <span className="kicker" style={{ marginTop: 24 }}>{record.lexeme.language.toUpperCase()} · defined term</span>
    <h1 dir="auto">{record.lexeme.text}</h1>
    {record.lexeme.transliteration && <p><strong>Transliteration:</strong> {record.lexeme.transliteration}</p>}
    <p><strong>Gloss:</strong> {record.lexeme.gloss || "No gloss is recorded in this dataset."}</p>
    <p>{record.lexeme.strongs_id && <span className="meta-tag">{record.lexeme.strongs_id}</span>} {record.lexeme.part_of_speech && <span className="meta-tag">{record.lexeme.part_of_speech}</span>}</p>
    {record.lexemeSources.length > 0 && <><h2>Lexicon references</h2><div className="claim-sources">{record.lexemeSources.map((item: any) => <SourceChip key={item.source.id} source={item.source} />)}</div><p>Glosses are concise orientation paraphrases. Consult the linked lexicon entry for senses, morphology, and context.</p></>}
    <h2>Deterministic values</h2>
    <div className="source-list">{record.values.map((value: any) => {
      const source: Source | null = value.method_source_id ? {
        id: value.method_source_id, type: value.method_source_type, title: value.method_source_title,
        author: value.method_source_author, year: value.method_source_year, url: value.method_source_url,
        archive_url: value.method_source_archive_url, reliability_grade: value.method_source_reliability_grade,
        access_note: value.method_source_access_note,
      } : null;
      return <section className="source-record" key={value.system_id}>
        <div className="source-record-button" style={{ cursor: "default" }}><span><h3>{value.system_name}</h3><span className="source-record-meta">{value.description}</span></span><span className="source-grade">{value.value.toLocaleString()} · root {value.reduced_value}</span></div>
        {source && <div className="claim-sources" style={{ marginTop: 10 }}><SourceChip source={source} /></div>}
      </section>;
    })}</div>
    {record.root && <><h2>Root record</h2><p><span dir="auto" style={{ fontFamily: "var(--hebrew-font)", fontSize: 22 }}>{record.root.text}</span> · {record.root.transliteration} · {record.root.gloss}</p></>}
    {record.etymology.length > 0 && <><h2>Cited etymology</h2>{record.etymology.map((entry: any) => <section className="claim-card" key={entry.id} style={{ marginTop: 9 }}>
      <div className="claim-card-top"><ConfidenceBadge tag={entry.confidence} /><span className="meta-tag">{entry.relation}</span></div><p>{entry.explanation}</p><div className="claim-sources"><SourceChip source={{ id: entry.source_id, type: "lexicon", title: entry.source_title, author: entry.author, year: entry.year, url: entry.source_url, archive_url: entry.archive_url, reliability_grade: "B", access_note: null }} /></div>
    </section>)}</>}
    <h2>Frequently asked questions</h2>
    <section className="faq-item"><h3>Are gematria values generated by AI?</h3><p>No. Values come from deterministic code and visible lookup tables.</p></section>
    <section className="faq-item"><h3>Does a shared value prove that words are connected?</h3><p>No. A shared value is a numerical observation only; inspect the current corpus baseline and seek independent historical evidence.</p></section>
    <p style={{ marginTop: 25 }}><strong>Educational research tool, not proof; patterns do not establish causation.</strong></p>
  </main>;
}
